# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moses/Main/WARRIOR/Goalkeeper/WARRIOR-Goalkeeper-PC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moses/Main/WARRIOR/Goalkeeper/WARRIOR-Goalkeeper-PC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moses/Main/WARRIOR/Goalkeeper/WARRIOR-Goalkeeper-PC/CMakeFiles /home/moses/Main/WARRIOR/Goalkeeper/WARRIOR-Goalkeeper-PC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moses/Main/WARRIOR/Goalkeeper/WARRIOR-Goalkeeper-PC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kamera

# Build rule for target.
kamera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kamera
.PHONY : kamera

# fast build rule for target.
kamera/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/build
.PHONY : kamera/fast

#=============================================================================
# Target rules for targets named segmentasi

# Build rule for target.
segmentasi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 segmentasi
.PHONY : segmentasi

# fast build rule for target.
segmentasi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/build
.PHONY : segmentasi/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named segmentation

# Build rule for target.
segmentation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 segmentation
.PHONY : segmentation

# fast build rule for target.
segmentation/fast:
	$(MAKE) $(MAKESILENT) -f gui/CMakeFiles/segmentation.dir/build.make gui/CMakeFiles/segmentation.dir/build
.PHONY : segmentation/fast

gui/KalibrasiKamera.o: gui/KalibrasiKamera.cpp.o
.PHONY : gui/KalibrasiKamera.o

# target to build an object file
gui/KalibrasiKamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/KalibrasiKamera.cpp.o
.PHONY : gui/KalibrasiKamera.cpp.o

gui/KalibrasiKamera.i: gui/KalibrasiKamera.cpp.i
.PHONY : gui/KalibrasiKamera.i

# target to preprocess a source file
gui/KalibrasiKamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/KalibrasiKamera.cpp.i
.PHONY : gui/KalibrasiKamera.cpp.i

gui/KalibrasiKamera.s: gui/KalibrasiKamera.cpp.s
.PHONY : gui/KalibrasiKamera.s

# target to generate assembly for a file
gui/KalibrasiKamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/KalibrasiKamera.cpp.s
.PHONY : gui/KalibrasiKamera.cpp.s

gui/PilihKamera.o: gui/PilihKamera.cpp.o
.PHONY : gui/PilihKamera.o

# target to build an object file
gui/PilihKamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/PilihKamera.cpp.o
.PHONY : gui/PilihKamera.cpp.o

gui/PilihKamera.i: gui/PilihKamera.cpp.i
.PHONY : gui/PilihKamera.i

# target to preprocess a source file
gui/PilihKamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/PilihKamera.cpp.i
.PHONY : gui/PilihKamera.cpp.i

gui/PilihKamera.s: gui/PilihKamera.cpp.s
.PHONY : gui/PilihKamera.s

# target to generate assembly for a file
gui/PilihKamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/gui/PilihKamera.cpp.s
.PHONY : gui/PilihKamera.cpp.s

kamera.o: kamera.cpp.o
.PHONY : kamera.o

# target to build an object file
kamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/kamera.cpp.o
.PHONY : kamera.cpp.o

kamera.i: kamera.cpp.i
.PHONY : kamera.i

# target to preprocess a source file
kamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/kamera.cpp.i
.PHONY : kamera.cpp.i

kamera.s: kamera.cpp.s
.PHONY : kamera.s

# target to generate assembly for a file
kamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/kamera.cpp.s
.PHONY : kamera.cpp.s

library/Algoritma.o: library/Algoritma.cpp.o
.PHONY : library/Algoritma.o

# target to build an object file
library/Algoritma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Algoritma.cpp.o
.PHONY : library/Algoritma.cpp.o

library/Algoritma.i: library/Algoritma.cpp.i
.PHONY : library/Algoritma.i

# target to preprocess a source file
library/Algoritma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Algoritma.cpp.i
.PHONY : library/Algoritma.cpp.i

library/Algoritma.s: library/Algoritma.cpp.s
.PHONY : library/Algoritma.s

# target to generate assembly for a file
library/Algoritma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Algoritma.cpp.s
.PHONY : library/Algoritma.cpp.s

library/Camera.o: library/Camera.cpp.o
.PHONY : library/Camera.o

# target to build an object file
library/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/library/Camera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Camera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Camera.cpp.o
.PHONY : library/Camera.cpp.o

library/Camera.i: library/Camera.cpp.i
.PHONY : library/Camera.i

# target to preprocess a source file
library/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/library/Camera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Camera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Camera.cpp.i
.PHONY : library/Camera.cpp.i

library/Camera.s: library/Camera.cpp.s
.PHONY : library/Camera.s

# target to generate assembly for a file
library/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kamera.dir/build.make CMakeFiles/kamera.dir/library/Camera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Camera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Camera.cpp.s
.PHONY : library/Camera.cpp.s

library/Citra.o: library/Citra.cpp.o
.PHONY : library/Citra.o

# target to build an object file
library/Citra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Citra.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Citra.cpp.o
.PHONY : library/Citra.cpp.o

library/Citra.i: library/Citra.cpp.i
.PHONY : library/Citra.i

# target to preprocess a source file
library/Citra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Citra.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Citra.cpp.i
.PHONY : library/Citra.cpp.i

library/Citra.s: library/Citra.cpp.s
.PHONY : library/Citra.s

# target to generate assembly for a file
library/Citra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/library/Citra.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Citra.cpp.s
.PHONY : library/Citra.cpp.s

library/InisiasiSerial.o: library/InisiasiSerial.cpp.o
.PHONY : library/InisiasiSerial.o

# target to build an object file
library/InisiasiSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/InisiasiSerial.cpp.o
.PHONY : library/InisiasiSerial.cpp.o

library/InisiasiSerial.i: library/InisiasiSerial.cpp.i
.PHONY : library/InisiasiSerial.i

# target to preprocess a source file
library/InisiasiSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/InisiasiSerial.cpp.i
.PHONY : library/InisiasiSerial.cpp.i

library/InisiasiSerial.s: library/InisiasiSerial.cpp.s
.PHONY : library/InisiasiSerial.s

# target to generate assembly for a file
library/InisiasiSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/InisiasiSerial.cpp.s
.PHONY : library/InisiasiSerial.cpp.s

library/KomunikasiMikro.o: library/KomunikasiMikro.cpp.o
.PHONY : library/KomunikasiMikro.o

# target to build an object file
library/KomunikasiMikro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/KomunikasiMikro.cpp.o
.PHONY : library/KomunikasiMikro.cpp.o

library/KomunikasiMikro.i: library/KomunikasiMikro.cpp.i
.PHONY : library/KomunikasiMikro.i

# target to preprocess a source file
library/KomunikasiMikro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/KomunikasiMikro.cpp.i
.PHONY : library/KomunikasiMikro.cpp.i

library/KomunikasiMikro.s: library/KomunikasiMikro.cpp.s
.PHONY : library/KomunikasiMikro.s

# target to generate assembly for a file
library/KomunikasiMikro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/KomunikasiMikro.cpp.s
.PHONY : library/KomunikasiMikro.cpp.s

library/Motion.o: library/Motion.cpp.o
.PHONY : library/Motion.o

# target to build an object file
library/Motion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Motion.cpp.o
.PHONY : library/Motion.cpp.o

library/Motion.i: library/Motion.cpp.i
.PHONY : library/Motion.i

# target to preprocess a source file
library/Motion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Motion.cpp.i
.PHONY : library/Motion.cpp.i

library/Motion.s: library/Motion.cpp.s
.PHONY : library/Motion.s

# target to generate assembly for a file
library/Motion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/Motion.cpp.s
.PHONY : library/Motion.cpp.s

library/UDPListen.o: library/UDPListen.cpp.o
.PHONY : library/UDPListen.o

# target to build an object file
library/UDPListen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPListen.cpp.o
.PHONY : library/UDPListen.cpp.o

library/UDPListen.i: library/UDPListen.cpp.i
.PHONY : library/UDPListen.i

# target to preprocess a source file
library/UDPListen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPListen.cpp.i
.PHONY : library/UDPListen.cpp.i

library/UDPListen.s: library/UDPListen.cpp.s
.PHONY : library/UDPListen.s

# target to generate assembly for a file
library/UDPListen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPListen.cpp.s
.PHONY : library/UDPListen.cpp.s

library/UDPSend.o: library/UDPSend.cpp.o
.PHONY : library/UDPSend.o

# target to build an object file
library/UDPSend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPSend.cpp.o
.PHONY : library/UDPSend.cpp.o

library/UDPSend.i: library/UDPSend.cpp.i
.PHONY : library/UDPSend.i

# target to preprocess a source file
library/UDPSend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPSend.cpp.i
.PHONY : library/UDPSend.cpp.i

library/UDPSend.s: library/UDPSend.cpp.s
.PHONY : library/UDPSend.s

# target to generate assembly for a file
library/UDPSend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/library/UDPSend.cpp.s
.PHONY : library/UDPSend.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

segmentasi.o: segmentasi.cpp.o
.PHONY : segmentasi.o

# target to build an object file
segmentasi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/segmentasi.cpp.o
.PHONY : segmentasi.cpp.o

segmentasi.i: segmentasi.cpp.i
.PHONY : segmentasi.i

# target to preprocess a source file
segmentasi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/segmentasi.cpp.i
.PHONY : segmentasi.cpp.i

segmentasi.s: segmentasi.cpp.s
.PHONY : segmentasi.s

# target to generate assembly for a file
segmentasi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segmentasi.dir/build.make CMakeFiles/segmentasi.dir/segmentasi.cpp.s
.PHONY : segmentasi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kamera"
	@echo "... main"
	@echo "... segmentasi"
	@echo "... segmentation"
	@echo "... gui/KalibrasiKamera.o"
	@echo "... gui/KalibrasiKamera.i"
	@echo "... gui/KalibrasiKamera.s"
	@echo "... gui/PilihKamera.o"
	@echo "... gui/PilihKamera.i"
	@echo "... gui/PilihKamera.s"
	@echo "... kamera.o"
	@echo "... kamera.i"
	@echo "... kamera.s"
	@echo "... library/Algoritma.o"
	@echo "... library/Algoritma.i"
	@echo "... library/Algoritma.s"
	@echo "... library/Camera.o"
	@echo "... library/Camera.i"
	@echo "... library/Camera.s"
	@echo "... library/Citra.o"
	@echo "... library/Citra.i"
	@echo "... library/Citra.s"
	@echo "... library/InisiasiSerial.o"
	@echo "... library/InisiasiSerial.i"
	@echo "... library/InisiasiSerial.s"
	@echo "... library/KomunikasiMikro.o"
	@echo "... library/KomunikasiMikro.i"
	@echo "... library/KomunikasiMikro.s"
	@echo "... library/Motion.o"
	@echo "... library/Motion.i"
	@echo "... library/Motion.s"
	@echo "... library/UDPListen.o"
	@echo "... library/UDPListen.i"
	@echo "... library/UDPListen.s"
	@echo "... library/UDPSend.o"
	@echo "... library/UDPSend.i"
	@echo "... library/UDPSend.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... segmentasi.o"
	@echo "... segmentasi.i"
	@echo "... segmentasi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

